// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhGXxeJ4mi1bIav-VEgKEICOauZl6pCvw',
    appId: '1:370115509126:web:c85d1abff8162a492aca07',
    messagingSenderId: '370115509126',
    projectId: 'e-commerce-1-68349',
    authDomain: 'e-commerce-1-68349.firebaseapp.com',
    storageBucket: 'e-commerce-1-68349.appspot.com',
    measurementId: 'G-FYPNPEMCHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBekURnKbqjNkkFhxyQ6ee4ZhzNqGDqTHM',
    appId: '1:370115509126:android:ec5a6f8e0d62f2a62aca07',
    messagingSenderId: '370115509126',
    projectId: 'e-commerce-1-68349',
    storageBucket: 'e-commerce-1-68349.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANBucslmha9sRwRCoTjbvPPb8yTlQxR_c',
    appId: '1:370115509126:ios:08d3dc3bd6e450572aca07',
    messagingSenderId: '370115509126',
    projectId: 'e-commerce-1-68349',
    storageBucket: 'e-commerce-1-68349.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANBucslmha9sRwRCoTjbvPPb8yTlQxR_c',
    appId: '1:370115509126:ios:08d3dc3bd6e450572aca07',
    messagingSenderId: '370115509126',
    projectId: 'e-commerce-1-68349',
    storageBucket: 'e-commerce-1-68349.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhGXxeJ4mi1bIav-VEgKEICOauZl6pCvw',
    appId: '1:370115509126:web:7c849ad47153f5152aca07',
    messagingSenderId: '370115509126',
    projectId: 'e-commerce-1-68349',
    authDomain: 'e-commerce-1-68349.firebaseapp.com',
    storageBucket: 'e-commerce-1-68349.appspot.com',
    measurementId: 'G-XKQTL9LZ0S',
  );
}
